packages:
    - examples/*
    - quickbundle
allowBuilds:
    unrs-resolver: false
minimumReleaseAgeExclude:
    - "@adbayb/stack"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
