packages:
    - examples/*
    - quickbundle
allowBuilds:
    unrs-resolver: true
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
