name: Continuous Integration

on: [push, pull_request]

jobs:
    install:
        timeout-minutes: 5
        name: Install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
    check:
        timeout-minutes: 5
        needs: install
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Check (lint, test, types)
              run: pnpm check
    build:
        timeout-minutes: 5
        needs: install
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
            - name: Use Node.js latest
              uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Build (library and examples)
              run: pnpm build
